name: 'Format'
description: 'Format the codebase'
runs:
  using: 'composite'
  steps:
    - name: 'Setup pnpm'
      uses: pnpm/action-setup@v4
      with:
        version: latest

    - name: 'Setup Node'
      uses: actions/setup-node@v4
      with:
        node-version: '20.11.1'
        cache: 'pnpm'

    - name: 'Install dependencies'
      shell: bash
      run: pnpm install

    - name: 'Format'
      shell: bash
      run: pnpm format