name: CI

on:
  pull_request:
    branches: ['*']
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FORCE_COLOR: 3

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        uses: ./.github/tooling/ci/lint

  format:
    runs-on: ubuntu-latest
    name: Format
    steps:
      - uses: actions/checkout@v4

      - name: Format
        uses: ./.github/tooling/ci/format

  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
      - uses: actions/checkout@v4

      - name: Typecheck
        uses: ./.github/tooling/ci/typecheck