name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - synchronize

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Slugify
        uses: rlespinasse/github-slug-action@v4.4.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
          cache: 'npm'

      - name: Pull Vercel Environment Information
        run: |
          npx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: |
          npx vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: |
          npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > domain.txt
          npx vercel alias --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} set `cat domain.txt` ${{ env.GITHUB_REF_SLUG_URL }}.think-feel-be-therapy.vercel.app
