name: Vercel Staging Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Build and Deploy to Vercel
        env:
          DOTENV_PRIVATE_KEY_DEVELOPMENT: ${{ secrets.DOTENV_PRIVATE_KEY_DEVELOPMENT }}
        run: |
          DEPLOYMENT_URL=$(pnpm dotenvx run -f .env.development -- pnpm dlx vercel --token=${{ secrets.VERCEL_TOKEN }})
          echo "DEPLOYMENT_URL=${DEPLOYMENT_URL}" >> $GITHUB_ENV

      - name: Alias Deployment
        run: |
          pnpm dlx vercel alias --token=${{ secrets.VERCEL_TOKEN }} set ${{ env.DEPLOYMENT_URL }} staging.thinkfeelbetherapy.com
